name: bleeding

on:
  push:
    branches:
      - bleeding
permissions:
  contents: write

jobs:
  release:
    name: new release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: specified version
        id: specified
        run: echo "SPECIFIED_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> "$GITHUB_OUTPUT"
      - name: Build with Maven
        run: mvn clean package
      - name: "new release"
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: 'target/api-*.jar'
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.specified.outputs.SPECIFIED_VERSION }}
          name: "Bleeding: ${{ steps.specified.outputs.SPECIFIED_VERSION }}"
          prerelease: true
